:: Clean.bat

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

:: Default path
set SolutionDir=.\

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

:: Set :: Folder names of source projects
set SrcProjectFolderNames=( ^
	Bundle ^
	InstallAssistant ^
	Msi ^
)

:: Delete dummy files that are generated by project build
for %%i in %SrcProjectFolderNames% do (
	rd "%SolutionDir%%%~i\Debug" /s /q
	rd "%SolutionDir%%%~i\Release" /s /q
	rd "%SolutionDir%%%~i\Win32" /s /q
	rd "%SolutionDir%%%~i\x86" /s /q
	rd "%SolutionDir%%%~i\x64" /s /q
	rd "%SolutionDir%%%~i\obj" /s /q
)

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

:: Delete dummy files of Solution (for VS2010 and VS2015)
rd "%SolutionDir%.vs" /s /q
rd "%SolutionDir%ipch" /s /q
del "%SolutionDir%*.suo" /f /q /a:h
del "%SolutionDir%*.sdf" /f /q
del "%SolutionDir%*.VC.db" /f /q

:: Delete dummy files that are generated by solution build
rd "%SolutionDir%Debug" /s /q
rd "%SolutionDir%Release" /s /q
rd "%SolutionDir%Win32" /s /q
rd "%SolutionDir%x86" /s /q
rd "%SolutionDir%x64" /s /q

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

@pause
